config/routes.rb
Rails.application.routes.draw do


  #管理者ログインのルート
  namespace :admin do
    get 'search/search'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

#ユーザーログインのルート
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

#通知機能のルート
  scope module: :public do
    resources :notifications, only: [:index, :destroy]
  end

  get "/users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe"

  patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal"

#管理者のルート
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :travels, only: [:index, :show, :edit, :update, :destroy] do
      resources :travel_comments, only: [:destroy]
    end
    get "search" => "search#search"
    post 'destroy_selected', to: 'travels#destroy_selected', as: 'destroy_selected_travels'
  end

#トップページのルート
  root to: "homes#top"

#投稿モデルのルート
  resources :travels do
    resources :travel_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
    delete :destroy_all, on: :collection
    collection do
      get "search"
    end
    collection do
       post 'destroy_selected', to: 'travels#destroy_selected', as: 'destroy_selected_travels'
     end
  end


#ゲストユーザーのルート
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

#ログインユーザーのルート
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    member do
      get :favorites
    end
    collection do
      get "search"
    end
  end

  #お問い合わせのルート
  scope module: :public do
resources :contacts, only: [:new, :create] do
  collection do
      post 'confirm'
      post 'back'
      get 'done'
  end
end
end
#地図機能のルート
  resource :map, only: [:show]

#DM機能のルート
  resources :chats, only: [:show, :create, :destroy]
  get "tagsearches/search", to: "tagsearches#search"
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#rails db:migrate
#rails db:migrate:reset
#cd Trip_history
#rails routes
#ssh -i ~/.ssh/practice-aws2.pem ec2-user@18.181.246.3
#rails s -e production
#kill $(cat tmp/pids/puma.pid)
#bundle exec rails assets:precompile RAILS_ENV=production
#mysql -u root -p -h rds-mysql-server.cxgo4cy0wddj.ap-northeast-1.rds.amazonaws.com
#ActiveRecord::Base.connection.execute("BEGIN TRANSACTION; END;")
#scp -i ~/.ssh/practice-aws2.pem ~/.ssh/id_rsa ec2-user@43.207.61.188:.ssh/id_rsa
#:wq
#rails db:migrate:status
#rm -rf db/migrate/20240422103417_hoge.rb
#touch db/migrate/20240422103417_hoge.rb
#rails db:migrate:down VERSION=20240422124504
#rm -rf db/migrate/
#rails destroy model モデル名
#git reset --hard

app/controllers/tagsearches_controller.rb
class TagsearchesController < ApplicationController
  def search
    @model = Travel  #search機能とは関係なし
    @word = params[:content]
    @travel_search = Travel.where("category LIKE?","%#{@word}%").page(params[:page]).per(50)
    @travels = Travel.all.page(params[:page]).per(50)
    @categories = Travel.unique_categories
    @travel_detail  = Travel.joins(:view_counts).group(:id).order('COUNT(view_counts.id) DESC').page(params[:page]).per(50).limit(4)
    render "tagsearches/tagsearch"
  end
end

app/helpers/tagsearches_helper.rb
module TagsearchesHelper
end

app/views/tagsearches/_tagsearch.html.erb
<div class="serch_form" >
  <table align="center">
    <tr>
      <div class="serch_form">
      <%= form_with url: tagsearches_search_path,method: :get, local: true do |f| %>
      <td><%= f.text_field :content %></td>
      <td><%= f.submit'タグ検索' %></td>
      <% end %>
      </div>
    </tr> 
  </table>  
</div>

app/views/tagsearches/tagsearch.html.erb
<div class="row">
  <div class="col">
    <div class='container'>
      <div class="row mt-3" style="border-bottom-width: 5px; border-bottom-style: solid; border-bottom-color: #b0c4de;">
        <h2 class="col">"<%= @word %>"の旅</h2>
        <form class="form-inline my-2 my-lg-0" action="<%= search_travels_path %>" method="get">
          <input class="form-control mr-sm-2 rounded-pill" type="search" name="keyword" placeholder="投稿を検索する" aria-label="Search">
          <button class="button-hover search" type="submit">検索</button>
        </form>
      </div>
      <%= render 'travels/index', travels: @travel_search %>
    </div>
  </div>

  <div class="col-3">
    <div class="mt-4" style="border: 3px solid; border-radius: 15px; height: 300px; background-color: #add8e6;">
      <h4 class="text-center my-2" style="border-bottom: 3px solid;">タグ一覧</h4>
      <%= render 'travels/tag', categories: @categories %>
    </div>
    <div class="text-center mt-2">閲覧数が多い旅</div>
    <%= render 'travels/view', travels: @travel_detail %>
  </div>
</div>