config/routes.rb
Rails.application.routes.draw do


  #管理者ログインのルート
  namespace :admin do
    get 'search/search'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

#ユーザーログインのルート
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

#通知機能のルート
  scope module: :public do
    resources :notifications, only: [:index, :destroy]
  end

  get "/users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe"

  patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal"

#管理者のルート
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :travels, only: [:index, :show, :edit, :update, :destroy] do
      resources :travel_comments, only: [:destroy]
    end
    get "search" => "search#search"
    post 'destroy_selected', to: 'travels#destroy_selected', as: 'destroy_selected_travels'
  end

#トップページのルート
  root to: "homes#top"

#投稿モデルのルート
  resources :travels do
    resources :travel_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
    delete :destroy_all, on: :collection
    collection do
      get "search"
    end
    collection do
       post 'destroy_selected', to: 'travels#destroy_selected', as: 'destroy_selected_travels'
     end
  end


#ゲストユーザーのルート
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

#ログインユーザーのルート
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    member do
      get :favorites
    end
    collection do
      get "search"
    end
  end

  #お問い合わせのルート
  scope module: :public do
resources :contacts, only: [:new, :create] do
  collection do
      post 'confirm'
      post 'back'
      get 'done'
  end
end
end
#地図機能のルート
  resource :map, only: [:show]

#DM機能のルート
  resources :chats, only: [:show, :create, :destroy]
  get "tagsearches/search", to: "tagsearches#search"
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#rails db:migrate
#rails db:migrate:reset
#cd Trip_history
#rails routes
#ssh -i ~/.ssh/practice-aws2.pem ec2-user@18.181.246.3
#rails s -e production
#kill $(cat tmp/pids/puma.pid)
#bundle exec rails assets:precompile RAILS_ENV=production
#mysql -u root -p -h rds-mysql-server.cxgo4cy0wddj.ap-northeast-1.rds.amazonaws.com
#ActiveRecord::Base.connection.execute("BEGIN TRANSACTION; END;")
#scp -i ~/.ssh/practice-aws2.pem ~/.ssh/id_rsa ec2-user@43.207.61.188:.ssh/id_rsa
#:wq
#rails db:migrate:status
#rm -rf db/migrate/20240422103417_hoge.rb
#touch db/migrate/20240422103417_hoge.rb
#rails db:migrate:down VERSION=20240422124504
#rm -rf db/migrate/
#rails destroy model モデル名
#git reset --hard

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :travels, dependent: :destroy #投稿モデル
  has_many :favorites, dependent: :destroy #いいねモデル
  has_one_attached :profile_image #アクティブストレージ(画像を扱う)

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # DM機能
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms

  # コメント機能
  has_many :travel_comments, dependent: :destroy

  # 通知機能
  has_many :notifications, dependent: :destroy

  #
  has_many :view_counts, dependent: :destroy

 #ユーザー情報のバリデーション
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :body, presence: true, length: { maximum: 300 }, allow_blank: true
  validates :name, presence: true, length: { maximum: 15 }


  # ゲストユーザーの処理
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.first_name = "ゲスト"
      user.last_name = "ユーザー"
      user.first_name_kana = "げすと"
      user.last_name_kana = "ゆーざー"
    end
  end

  def guest?
    email == GUEST_USER_EMAIL
  end

#投稿の並び替えの処理
  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :favorite, -> { joins(:favorites).order("favorites.count DESC") }

  def full_name
    first_name + '' + last_name
  end

  def full_name_kana
    first_name_kana + '' + last_name_kana
  end

  def user_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  def favorite_travels
    Travel.joins(:favorites).where(favorites: { user_id: self.id })
  end

  # 退会機能
  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

#ユーザー検索の処理
def self.search(search)
  if search.present?
    User.where('name LIKE ?', "%#{search}%")
  else
    User.all
  end
end

# 管理者検索の処理
def self.admin_search(search)
  if search.present?
    User.where('name LIKE ? OR last_name LIKE ? OR first_name LIKE ? OR last_name_kana LIKE ? OR first_name_kana LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  else
    User.all
  end
end


  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # 画像を扱う処理
  def get_profile_image
    profile_image.attached? ? profile_image : 'Untitled_logo_1_free-file.jpg'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.all.page(params[:page]).per(20)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: "ユーザーを削除しました。"
  end
  
    private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :is_deleted)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]

  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @user_travels = @user.travels.page(params[:page]).per(12)
    @categories = Travel.unique_categories
    @travel_detail  = Travel.joins(:view_counts).group(:id).order('COUNT(view_counts.id) DESC').page(params[:page]).per(50).limit(4)
  end

  def search
    @user = current_user
    @users = User.search(params[:keyword]).page(params[:page]).per(20)
  end

  def index
    @users = User.all.page(params[:page]).per(12)
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    @travel = @user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      @travels = Travel.all
      @travel = Travel.new
      render :edit
    end
  end

  def favorites
    if params[:latest]
      @favorite_travels = current_user.favorite_travels.latest.page(params[:page]).per(12)
    elsif params[:old]
      @favorite_travels = current_user.favorite_travels.old.page(params[:page]).per(12)
    elsif params[:favorite]
      @favorite_travels = current_user.favorite_travels.includes(:favorites).order('favorites.created_at DESC').sort_by { |travel| travel.favorites.count }.reverse
      @favorite_travels = Kaminari.paginate_array(@favorite_travels).page(params[:page]).per(12)
    else
      @favorite_travels = current_user.favorite_travels.page(params[:page]).per(12)
    end
    @categories = Travel.unique_categories
    @travel_detail  = Travel.joins(:view_counts).group(:id).order('COUNT(view_counts.id) DESC').page(params[:page]).per(50).limit(4)
  end

  def unsubscribe

  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_deleted: true) #is_deletedカラムをtrueに変更することにより削除フラグを立てる
    reset_session
    flash[:notice] = "退会処理を実行しました。"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :body)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.email == "guest@example.com"
      redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end

  def is_matching_login_user
    if current_user.nil? || params[:id].to_i != current_user.id
      redirect_to root_path
    end
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<head>
  <style>
    .scrollable {
      max-height: 400px;
      overflow-y: scroll;
      scrollbar-width: thin;
      scrollbar-color: transparent transparent;
    }

  </style>
</head>
<div class="scrollable" style="overflow: auto; max-height: 400px;">

    <% users.each do |user| %>
      <div class="row mt-4" style="border-bottom-width: 3px; border-bottom-style: dotted; border-bottom-color: #a9a9a9;">
        <div class="col-1"><%= image_tag user.get_profile_image, class: "rounded-circle", size: '50x50' %></div>
        <div class="col-2"><%= user.name.truncate(7) %></div>
        <div class="col-2">フォロワー数: <%= user.followers.count %></div>
        <div class="col-3" id="follow-ajax_<%= user.id %>">
          <% if current_user.following?(user) %>
            <%= link_to user_relationships_path(user.id), class: "button-hover", style: "z-index: 9998;", method: :delete, remote: true do %>
              フォローを外す&nbsp;&nbsp;<i class="fa-solid fa-user-minus"></i>
            <% end %>
          <% else %>
            <%= link_to user_relationships_path(user.id), class: "button-hover", style: "z-index: 9998;", method: :post, remote: true do %>
              フォローする&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa-solid fa-user-plus"></i>
            <% end %>
          <% end %>
        </div>
          <div class="box col-4 mb-2">
            <%= link_to user_path(user.id), class: "" do %>
              <div id="travel_home">
                <div class="layer2">
                  <div class="nb">この旅人の部屋へ<i class="fa-solid fa-door-open"></i></div>
                </div>
                <div class="textlink">Go to room</div>
              </div>
            <% end %>
          </div>

      </div>
    <% end %>
</div>

app/views/users/_info.html.erb
<head>
  <style>
    .parent-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
    }
  </style>
</head>
<div id="container" class="parent-container" style="background-color: #f0f8ff; border-radius: 10px;padding: 20px 30px; box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.3); width:950px; margin-left:80px;">
  <div class="row">
    <div class="col">
      <%= image_tag user.get_profile_image, class: "rounded-circle mt-3 mr-1", size: '150x150' %>
      <h4 class="text-align: center; mt-3">
        <%= user.name %>
      </h4>
    </div>
    <div class="col">
      <%= link_to "フォロー一覧", user_followings_path(user), class: "button-hover mt-5", style: "z-index: 9998;" %>
      &nbsp;&nbsp;
      <%= link_to "フォロワー一覧", user_followers_path(user), class: "button-hover", style: "z-index: 9998;" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container mt-2'>
  <%= render 'layouts/errors' %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 mx-auto">
      <h2>プロフィール編集</h2>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :プロフィール名 %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :プロフィール画像 %>
          <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
        </div>
        <div class="form-group">
          <h4>自己紹介</h4>
          <%= f.text_area :body, class: "form-control body", rows: '10' %>
        </div>
        <div class="form-group">
          <%= f.button '内容を保存する', class: 'button-hover edit' %>
        </div>
      <% end %>
      <%= link_to "退会する", unsubscribe_path, class: "button edit" %>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="row">
  <div class="col">
    <div class="container">
      <div class="row mt-3" style="border-bottom-width: 5px; border-bottom-style: solid; border-bottom-color: #b0c4de;">
        <h2 class="col">いいねした旅一覧</h2>
        <form class="form-inline my-2 my-lg-0" action="<%= search_travels_path %>" method="get">
          <input class="form-control mr-sm-2 rounded-pill" type="search" name="keyword" placeholder="投稿を検索する" aria-label="Search">
          <button class="button-hover search" type="submit">検索</button>
        </form>
      </div>

      <div class="dropdown mt-3">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          並び替え
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <button class="dropdown-item" type="button"><%= link_to '新しい順', { latest: true } %></button>
          <button class="dropdown-item" type="button"><%= link_to '古い順', { old: true } %></button>
          <button class="dropdown-item" type="button"><%= link_to 'いいね順', { favorite: true } %></button>
        </div>
        <script>
          $(document).ready(function() {
            $('.dropdown-item').click(function() {
              var link = $(this).children('a').attr('href');
              window.location.href = link;
            });
          });
        </script>
      </div>

      <%= render 'travels/index', travels: @favorite_travels %>
      <div class="flex justify-end">
        <%= paginate @favorite_travels %>
      </div>
    </div>
  </div>

  <div class="col-3">
    <div class="mt-4" style="border: 3px solid; border-radius: 15px; height: 300px; background-color: #add8e6;">
      <h4 class="text-center my-2" style="border-bottom: 3px solid;">タグ一覧</h4>
      <%= render 'travels/tag', categories: @categories %>
    </div>
    <div class="text-center mt-2">閲覧数が多い旅</div>
    <%= render 'travels/view', travels: @travel_detail %>
  </div>
</div>

app/views/users/index.html.erb
 <%= render 'info', user: @user %>
  <div class="row justify-content-center mt-3">
    <div class="col-10" style="background-color: #f0f8ff; border-radius: 10px;padding: 20px 30px; box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.3);">
      <div class="row mt-3" style="border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #a9a9a9; padding: 10px 0px 0px 0px;">
        <h2 class="col text-center">旅人一覧</h2>
        <div class="col">
         <form class="form-inline my-2 my-lg-0" action="<%= search_users_path %>" method="get">
           <input class="form-control mr-sm-2 rounded-pill" type="search" name="keyword" placeholder="旅人を探す" aria-label="Search">
            <button class="button-hover search" type="submit" style="z-index: 9998;">検索</button>
           </form>
        </div>
      </div>
      <%= render 'users/index',users: @users %>
      <div class="d-flex justify-content-center">
        <%= paginate @users %>
      </div>
    </div>
  </div>

app/views/users/search.html.erb
  <%= render 'info', user: @user %>
  <div class='row justify-content-center mt-3'>
    <div class='col-10'style="background-color: #f0f8ff; border-radius: 10px;padding: 20px 30px; box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.3);">
      <div class="row mt-3" style="border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #a9a9a9; padding: 10px 0px 0px 0px;">
        <h2 class="col text-center">発見した旅人</h2>
        <div class="col">
          <form class="form-inline my-2 my-lg-0" action="<%= search_users_path %>" method="get">
            <input class="form-control mr-sm-2 rounded-pill" type="search" name="keyword" placeholder="旅人を探す" aria-label="Search">
            <button class="button-hover search" type="submit">検索</button>
          </form>
        </div>
      </div>
      <%= render 'users/index',users: @users %>
      <div class="flex justify-end">
        <%= paginate @users %>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<head>
  <style>
    .break-text {
      word-wrap: break-word;
      width: 100%;
    }

    .triangle {
      width: 10px;
      height: 10px;
      border-left: 25px solid transparent;
      border-right: 30px solid transparent;
      border-bottom: 20px solid lightgray;
    }
  </style>
</head>
<form action="<%= destroy_selected_travels_travels_path %>" method="post" id="delete_selected_form" data-turbo-frame="false">
  <div class="row">
    <div class="col-9">
      <div class='container'>

        <div class="row mt-3" style="background-color: #f0f8ff; border-radius: 10px; padding: 20px 30px; box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.3);">
          <div class="col-1 mr-4">
            <%= image_tag @user.get_profile_image, class: "rounded-circle", size: '100x100' %>
          </div>
          <div class="col">
            <div class="row">
              <h4 class="col ml-5" style="border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: #a9a9a9; padding: 10px 0px 0px 30px;">
                <%= @user.name %>さんの部屋
              </h4>

              <% if current_user != @user && current_user.following?(@user) && @user.following?(current_user) %>
              <div class="box mb-2" id="travel_home" style="margin-right: 140px;">
                <%= link_to chat_path(@user.id), class: "" do %>
                <div id="travel_home">
                  <div class="layer2">
                    <div class="nb"><i class="fa-regular fa-comments"></i>&nbsp;&nbsp;DMする</div>
                  </div>
                  <div class="textlink">send a DM</div>
                </div>
                <% end %>
              </div>
              <% end %>

              <% if current_user == @user %>
              <div class="box mb-2" id="travel_home" style="margin-right: 140px;">
                <%= link_to edit_user_path(current_user), method: :get, class: "" do %>
                <div id="travel_home">
                  <div class="layer2">
                    <div class="nb">
                      <i class="fa-regular fa-address-card"></i>&nbsp;&nbsp;プロフィールを編集
                    </div>
                  </div>
                  <div class="textlink">make an edit</div>
                </div>
                <% end %>
              </div>
              <% end %>
            </div>
          </div>
          <% if @user.body.present? %>
          <div>
            <div class="triangle ml-4 mt-2"></div>
            <p class="break-text" style="background-color: lightgray; padding: 8px; border-radius: 18px 20px 20px 20px;">
              <%= @user.body %>
            </p>
          </div>
          <% end %>
        </div>

        <div class="row my-3" style="border-bottom-width: 5px; border-bottom-style: solid; border-bottom-color: #b0c4de;">
          <h3 class="col-9"><%= @user.name %>さんの旅一覧</h3>
        </div>
        <% if current_user == @user %>
        <div class="row">
          <%= link_to destroy_all_travels_path, method: :delete, data: { confirm: '本当に全ての旅行データを削除しますか？' }, class: "button" do %>
          全て削除&nbsp;&nbsp;<i class="fa-solid fa-trash-can"></i>
          <% end %>
          &nbsp;&nbsp;&nbsp;&nbsp;
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button type="submit" class="button" data-turbo-frame="false">選択項目を削除<i class="fa-solid fa-trash-can"></i></button>
          <div class="col">
            <%= link_to new_travel_path, class: 'button-hover' do %>
            <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;新しく投稿する
            <% end %>
          </div>
        </div>
        <% end %>
        <%= render 'travels/index', travels: @user_travels %>
        <%= paginate @user_travels %>
      </div>
    </div>
    <div class="col-3">
      <div class="mt-4" style="border: 3px solid; border-radius: 15px; height: 300px; background-color: #add8e6;">
        <h4 class="text-center my-2" style="border-bottom: 3px solid;">タグ一覧</h4>
        <%= render 'travels/tag', categories: @categories %>
      </div>
      <h4 class="text-center mt-2">閲覧数が多い旅</h4>
      <%= render 'travels/view', travels: @travel_detail %>
    </div>
  </div>
</form>

app/views/users/unsubscribe.html.erb
<div class='container text-center'>
  <div class='text-center'>
 <h2 style="border-bottom-width: 5px; border-bottom-style: solid; border-bottom-color: #b0c4de; padding-top: 10px; padding-bottom: 10px;">退会お手続き</h2>
 <h3 class="mt-4">
   退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
   再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
   本当に退会してよろしいですか？
 </h3>
<div class="row">
 <div class="col-6">
  <%= link_to "退会する", withdrawal_path, method: :patch, data: { confirm: "本当に退会しますか？" },class: 'button ml-auto mt-2' %>
</div>
<div class="col-6">
<%= link_to "退会しない", edit_user_path(current_user),class: 'button-hover mr-auto mt-2' %>
</div>
</div>
</div>
  </div>
</div>