config/routes.rb
Rails.application.routes.draw do


  #管理者ログインのルート
  namespace :admin do
    get 'search/search'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

#ユーザーログインのルート
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

#通知機能のルート
  scope module: :public do
    resources :notifications, only: [:index, :destroy]
  end

  get "/users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe"

  patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal"

#管理者のルート
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :travels, only: [:index, :show, :edit, :update, :destroy] do
      resources :travel_comments, only: [:destroy]
    end
    get "search" => "search#search"
    post 'destroy_selected', to: 'travels#destroy_selected', as: 'destroy_selected_travels'
  end

#トップページのルート
  root to: "homes#top"

#投稿モデルのルート
  resources :travels do
    resources :travel_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
    delete :destroy_all, on: :collection
    collection do
      get "search"
    end
    collection do
       post 'destroy_selected', to: 'travels#destroy_selected', as: 'destroy_selected_travels'
     end
  end


#ゲストユーザーのルート
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

#ログインユーザーのルート
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    member do
      get :favorites
    end
    collection do
      get "search"
    end
  end

  #お問い合わせのルート
  scope module: :public do
resources :contacts, only: [:new, :create] do
  collection do
      post 'confirm'
      post 'back'
      get 'done'
  end
end
end
#地図機能のルート
  resource :map, only: [:show]

#DM機能のルート
  resources :chats, only: [:show, :create, :destroy]
  get "tagsearches/search", to: "tagsearches#search"
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#rails db:migrate
#rails db:migrate:reset
#cd Trip_history
#rails routes
#ssh -i ~/.ssh/practice-aws2.pem ec2-user@18.181.246.3
#rails s -e production
#kill $(cat tmp/pids/puma.pid)
#bundle exec rails assets:precompile RAILS_ENV=production
#mysql -u root -p -h rds-mysql-server.cxgo4cy0wddj.ap-northeast-1.rds.amazonaws.com
#ActiveRecord::Base.connection.execute("BEGIN TRANSACTION; END;")
#scp -i ~/.ssh/practice-aws2.pem ~/.ssh/id_rsa ec2-user@43.207.61.188:.ssh/id_rsa
#:wq
#rails db:migrate:status
#rm -rf db/migrate/20240422103417_hoge.rb
#touch db/migrate/20240422103417_hoge.rb
#rails db:migrate:down VERSION=20240422124504
#rm -rf db/migrate/
#rails destroy model モデル名
#git reset --hard

app/controllers/admin/search_controller.rb
class Admin::SearchController < ApplicationController
  def search
    @travels = Travel.search(params[:keyword]).page(params[:page]).per(5)
   @users = User.admin_search(params[:keyword]).page(params[:page]).per(5)
  end
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/search/search.html.erb
<head>
  <style>
    .scrollable {
      max-height: 600px;
      overflow-y: scroll;
      scrollbar-width: thin; /* スクロールバーの幅を調整するためのプロパティ */
      scrollbar-color: transparent transparent; /* スクロールバーの色を透明にするためのプロパティ */
    }
        .scale {
  transition: transform 0.3s ease-in-out;
}

.scale:hover {
  box-shadow: 0px 0px 15px 2px rgba(0, 0, 0, 0.2);
  transform: scale(1.1);
}

.img{
  border-radius: 40px 40px 0px 0px;
}
  </style>
</head>
<div class='container'>
  <% if @travels.present? %>
<div class="scrollable" style="overflow: auto; max-height: 600px;" id="app-container">
  <h3 class="text-center">投稿一覧</h3>
  <% @travels.each_slice(3) do |travels_slice| %>
    <div class="container">
      <div class="row justify-content-start" style="margin-left: 105px;">

        <% travels_slice.each do |travel| %>
          <div class="mt-4 mr-5 mb-4 border scale" style="width: 240px; display: inline-block; background-color: #f0fff0; border-radius: 40px 40px 40px 40px;">
            <% if travel.image.attached? %>
              <%= image_tag travel.image, class: "img", size: "240x150" %>
            <% else %>
              <%= image_tag 'Untitled_logo_1_free-file.jpg', class: "img", size: "240x150" %>
            <% end %>

            <h4 class="text-center">
              <%= link_to (travel.title.length > 10) ? "#{travel.title[0..9]}..." : travel.title, admin_travel_path(travel) %>
            </h4>
            <div style="padding: 0px 20px 0px 20px">
              <div class="">
                <% if current_user && travel.user == current_user %>
                  <%= image_tag current_user.get_profile_image, size: '40x40', class: 'rounded-circle' %><%= travel.user.name %>
                <% else %>
                  <%= image_tag travel.user.get_profile_image, size: '40x40', class: 'rounded-circle' %><%= travel.user.name %>
                <% end %>
              </div>
              <div class="row">
                <p class="col" id="comment_counter">
                  <%= render "travel_comments/counter", travel: travel %>
                </p>
              </div>

              <div class="row">
                <p class="col">
                  <% if travel.category.present? %>
                    <%= travel.category %>
                  <% end %>
                </p>
                <div class="col">
                  <div class="row">
                    <%= link_to edit_admin_travel_path(travel.id), method: :get, class: "button-hover index col" do %>
                      <i class="fa-solid fa-pen-to-square"></i>
                    <% end %>

                    <%= link_to admin_travel_path(travel.id), method: :delete, class: "button index col", "data-confirm" => "本当に削除しますか？" do %>
                      <i class="fa-solid fa-trash-can"></i>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="col">
                <%= travel.created_at.strftime('%Y/%m/%d %H:%M') %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<%= paginate @travels %>
  <% else %>
         <table class="table table-borderless">
    <tr style="border-bottom-width: 4px; border-bottom-style: solid; border-bottom-color: #b0c4de; padding-top: 10px; padding-bottom: 10px;">
      <th></th>
      <th>登録名</th>
      <th>プロフィール名</th>
      <th>メールアドレス</th>
      <th>投稿総数</th>
      <th>フォロワー総数</th>
      <th>退会処理</th>
    </tr>
    <% @users.each do |user| %>
      <tr style="border-bottom-width: 4px; border-bottom-style: solid; border-bottom-color: #b0c4de; padding-top: 10px; padding-bottom: 10px;">
        <td><%= image_tag user.get_profile_image, class: "rounded-circle", size: '50x50' %></td>
        <td><%= link_to "#{user.first_name}#{user.last_name}", admin_user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>投稿数： <%= user.travels.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <%= link_to "退会させる", admin_user_path(user), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm" %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= paginate @users %>
  <% end %>
</div>