config/routes.rb
Rails.application.routes.draw do


  #管理者ログインのルート
  namespace :admin do
    get 'search/search'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

#ユーザーログインのルート
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

#通知機能のルート
  scope module: :public do
    resources :notifications, only: [:index, :destroy]
  end

  get "/users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe"

  patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal"

#管理者のルート
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :travels, only: [:index, :show, :edit, :update, :destroy] do
      resources :travel_comments, only: [:destroy]
    end
    get "search" => "search#search"
    post 'destroy_selected', to: 'travels#destroy_selected', as: 'destroy_selected_travels'
  end

#トップページのルート
  root to: "homes#top"

#投稿モデルのルート
  resources :travels do
    resources :travel_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
    delete :destroy_all, on: :collection
    collection do
      get "search"
    end
    collection do
       post 'destroy_selected', to: 'travels#destroy_selected', as: 'destroy_selected_travels'
     end
  end


#ゲストユーザーのルート
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

#ログインユーザーのルート
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    member do
      get :favorites
    end
    collection do
      get "search"
    end
  end

  #お問い合わせのルート
  scope module: :public do
resources :contacts, only: [:new, :create] do
  collection do
      post 'confirm'
      post 'back'
      get 'done'
  end
end
end
#地図機能のルート
  resource :map, only: [:show]

#DM機能のルート
  resources :chats, only: [:show, :create, :destroy]
  get "tagsearches/search", to: "tagsearches#search"
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#rails db:migrate
#rails db:migrate:reset
#cd Trip_history
#rails routes
#ssh -i ~/.ssh/practice-aws2.pem ec2-user@18.181.246.3
#rails s -e production
#kill $(cat tmp/pids/puma.pid)
#bundle exec rails assets:precompile RAILS_ENV=production
#mysql -u root -p -h rds-mysql-server.cxgo4cy0wddj.ap-northeast-1.rds.amazonaws.com
#ActiveRecord::Base.connection.execute("BEGIN TRANSACTION; END;")
#scp -i ~/.ssh/practice-aws2.pem ~/.ssh/id_rsa ec2-user@43.207.61.188:.ssh/id_rsa
#:wq
#rails db:migrate:status
#rm -rf db/migrate/20240422103417_hoge.rb
#touch db/migrate/20240422103417_hoge.rb
#rails db:migrate:down VERSION=20240422124504
#rm -rf db/migrate/
#rails destroy model モデル名
#git reset --hard

app/views/layouts/_background.html.erb
<head>
  <style>
@import url('https://fonts.googleapis.com/css?family=Exo:400,700');

*{
    margin: 0px;
    padding: 0px;
}

body{
    font-family: 'Exo', sans-serif;
}


.context {
    width: 100%;
    position: absolute;
    top:50vh;

}

.context h1{
    text-align: center;
    color: #fff;
    font-size: 50px;
}


.area{
    background: #add8e6;
    background: -webkit-linear-gradient(to left, #8f94fb, #4e54c8);
    width: 100%;
    height:100vh;


}

.circles{
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
}

.circles li{
    position: absolute;
    display: block;
    list-style: none;
    animation: animate 25s linear infinite;
    bottom: -180px;

}

.circles li:nth-child(1){
    left: 25%;
    animation-delay: 0s;
    font-size: 80px;
}


.circles li:nth-child(2){
    left: 10%;
    animation-delay: 2s;
    animation-duration: 12s;
    font-size: 20px;
}

.circles li:nth-child(3){
    left: 70%;
    animation-delay: 4s;
    font-size: 20px;
}

.circles li:nth-child(4){
    left: 40%;
    animation-delay: 0s;
    animation-duration: 18s;
    font-size: 60px;
}

.circles li:nth-child(5){
    left: 65%;
    animation-delay: 0s;
    font-size: 20px;
}

.circles li:nth-child(6){
    left: 75%;
    animation-delay: 3s;
    font-size: 110px;
}

.circles li:nth-child(7){
    left: 35%;
    animation-delay: 7s;
    font-size: 150px;
}

.circles li:nth-child(8){
    left: 50%;
    animation-delay: 15s;
    animation-duration: 45s;
     font-size: 25px;
}

.circles li:nth-child(9){
    left: 20%;
    animation-delay: 2s;
    animation-duration: 35s;
    font-size: 15px;
}

.circles li:nth-child(10){
    left: 85%;
    animation-delay: 0s;
    animation-duration: 11s;
    font-size: 150px;
}



@keyframes animate {

    0%{
        transform: translateY(0) rotate(0deg);
        opacity: 1;
        border-radius: 0;
    }

    100%{
        transform: translateY(-1000px) rotate(720deg);
        opacity: 0;
        border-radius: 50%;
    }

}
  </style>
</head>
<div class="context">

</div>
<div class="area">
    <ul class="circles">
        <li><i class="fa-solid fa-suitcase-rolling"></i></li>
        <li><i class="fa-solid fa-car"></i></li>
        <li><i class="fa-solid fa-camera"></i></li>
        <li><i class="fa-solid fa-plane"></i></li>
        <li><i class="fa-solid fa-bicycle"></i></li>
        <li><i class="fa-solid fa-train-subway"></i></li>
        <li><i class="fa-solid fa-thermometer"></i></li>
        <li><i class="fa-solid fa-mobile-screen"></i></li>
        <li><i class="fa-solid fa-map-location"></i></li>
        <li><i class="fa-solid fa-kitchen-set"></i></li>
    </ul>
</div>
<script>
  /*
  Background Gradients From --
  https://uigradients.com
  */
</script>

app/views/layouts/_click.html.erb
<head>
  <style>
    .btn {
  display: inline-block;
  position: relative;
  top: 0;
  left: 0;
  height: 50px;
  padding: 0 50px;
  background: #06a309;
  border-radius: 3px;
  text-align: center;
  color: #fff;
  line-height: 50px;
  overflow: hidden;
  transition: all 0.3s ease-in;
}
.btn:hover {
  background: #2abc27;
}

.btn.active {
  background: #2abc27;
}

.btn:active span::after {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 100px;
  height: 100px;
  margin-top: -50px;
  margin-left:-50px;
  content: "";
  background: #3bcc3b;
  border-radius: 100%;
  opacity: 0;
  animation: ripple 0.3s 1 ease-out;
}


@keyframes ripple {
  0% {
    opacity: 1;
    transform: scale(0.0);
  }

  100% {
    opacity: 1;
    transform: scale(1.0);
  }
}
  </style>
  </head>
<button class="btn"><span>BUTTON</span></button>
<script>
  $(function() {
  var $touch = $(".btn");
  $touch.click(function() {
    $touch.addClass('active');
    setTimeout(function() {
    $touch.removeClass('active');
    }, 300);
  });
});
</script>

app/views/layouts/_errors.html.erb
<% if @travel.errors.any? %>
  <%= @travel.errors.count %>件のエラーが発生しました
  <ul>
    <% @travel.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
 <p class="text-center mt-5">© Trip_history 2021. All rights reserved.</p>
<h5 style="text-align: right;" ><%= link_to "お問い合わせ", new_contact_path, style: "color: #fffacd; font-weight: bold; text-shadow: 1px 2px 3px #808080;" %></h5>

app/views/layouts/_header.html.erb
<head>
  <style>
    .navbar {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 70px;
    }

    .center-align {
      /* 真ん中に配置するためのスタイル定義 */
    }

    .centered-logo {
      margin-left: auto;
      margin-right: auto;
    }
  </style>
</head>

<div class="navbar center-align" style="background-color: #008b8b;">

    <%= link_to root_path do %>
    <%= render 'layouts/logo' %>
  <% end %>

  <% if user_signed_in? %>
    <%= render 'layouts/nav' %>
  <% elsif admin_signed_in? %>
    <div class="navbar right-align-item">
      <form class="form-inline my-2 my-lg-0" action="<%= admin_search_path %>" method="get">
        <input class="form-control mr-sm-2 rounded-pill" type="search" name="keyword" placeholder="キーワードを入力" aria-label="Search">
        <button class="btn btn-light rounded-pill mr-3" type="submit">検索</button>
      </form>
    </div>
  <% end %>
</div>

app/views/layouts/_headernav.html.erb
<head>
    <style>
      .nav-item{
        margin : 0px 10px 0px 10px;
      }


.nav-link {
  display: flex;
  align-items: center;
  justify-content: center;

  height: 45px;
  width: 200px;
  padding: 20px 0;
  border-radius: 6px;
  background-repeat: no-repeat;
  background-position: 100% 0;
  background-size: 200% auto;
  background-image: linear-gradient(
    to right,
    #a48c61 0%,
    #a48c61 50%,
    #eee8aa 50%,
    #eee8aa 100%
  );
  box-shadow: 0 3px 10px rgb(0 0 0 / 16%);
  transition: background-position ease 0.4s;
  text-align: center;
  color: #778899;
  text-decoration: none;
  font-weight: bold;
  font-size: 17px;
}

.nav-link:hover {
  background-position: 0 0;
  text-decoration: none;
  color: #fff;
}

    </style>
  </head>
<nav class="navbar navbar-expand-lg" style="width: 80%; margin: 0 auto;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 <div class="collapse navbar-collapse text-center" id="navbarNav">
    <ul class="navbar-nav mx-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_path(current_user), class: "nav-link"  do %>
            <i class="fas fa-home"></i> 旅人の部屋
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path, class: 'nav-link' do %>
            <i class="fas fa-users"></i> 旅人一覧
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to travels_path, class: 'nav-link' do %>
            <i class="fa-solid fa-suitcase-rolling"></i> 旅一覧
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to favorites_user_path(current_user), class: 'nav-link' do %>
            <i class="fa-solid fa-thumbs-up"></i> いいねした旅
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
            <i class="fas fa-sign-out-alt"></i> ログアウト
          <% end %>
        </li>
      <% elsif admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "投稿一覧", admin_travels_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "ユーザー一覧", admin_users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <i class="fas fa-home"></i> トップページ
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: 'nav-link' do %>
            <i class="fas fa-user-plus"></i> 新規登録
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: 'nav-link' do %>
            <i class="fas fa-sign-in-alt"></i> ログイン
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_logo.html.erb
<head>
<style>
@import url('https://fonts.googleapis.com/css2?family=Josefin+Sans&amp;display=swap');

.title {
display: flex;
overflow: hidden;
color: #fafad2;
font-family: 'Josefin Sans', sans-serif;
}

.title span {
display: block;
transform: translateY(0);
transition: transform cubic-bezier(0.215, 0.61, 0.355, 1) 0.5s;
}

.title.-visible span {
transform: translateY(100%);
}

.title span:nth-child(2) {
transition-delay: 0.06s;
}
.title span:nth-child(3) {
transition-delay: 0.12s;
}
.title span:nth-child(4) {
transition-delay: 0.18s;
}
.title span:nth-child(5) {
transition-delay: 0.24s;
}
.title span:nth-child(6) {
transition-delay: 0.30s;
}
.title span:nth-child(7) {
transition-delay: 0.36s;
}
.title span:nth-child(8) {
transition-delay: 0.42s;
}
.title span:nth-child(9) {
transition-delay: 0.48s;
}
.title span:nth-child(10) {
transition-delay: 0.54s;
}
.title span:nth-child(11) {
transition-delay: 0.6s;
}
.title span:nth-child(12) {
transition-delay: 0.66s;
}
</style>
</head>
<body>
<h1 class="title mt-2">
<span>T</span>
<span>r</span>
<span>i</span>
<span>p</span>
<span>&nbsp;</span>
<span>H</span>
<span>i</span>
<span>s</span>
<span>t</span>
<span>o</span>
<span>r</span>
<span>y</span>
</h1>
<script>
const CLASSNAME = "-visible";
const $target = $(".title");
let isLoggedIn;

toggleTitle();

function toggleTitle() {
  if (typeof isLoggedIn === "undefined") {
    isLoggedIn = <%= current_user.present?.to_json %>;
  }
  const TIMEOUT = isLoggedIn ? 3000 : 0;
  $target.addClass(CLASSNAME);
  setTimeout(() => {
    $target.removeClass(CLASSNAME);
  }, TIMEOUT);
}
</script>
</body>

app/views/layouts/_nav.html.erb
<head>
    <style>
/*　ハンバーガーメニューボタン　*/
.hamburger {
  display : block;
  position: fixed;
  z-index : 3;
  right : 20px;
  top   : 20px;
  width : 42px;
  height: 42px;
  cursor: pointer;
  text-align: center;
}
.hamburger span {
  display : block;
  position: absolute;
  width   : 30px;
  height  : 2px ;
  left    : 6px;
  background : #BBBBBB;
  -webkit-transition: 0.3s ease-in-out;
  -moz-transition   : 0.3s ease-in-out;
  transition        : 0.3s ease-in-out;
}
.hamburger span:nth-child(1) {
  top: 10px;
}
.hamburger span:nth-child(2) {
  top: 20px;
}
.hamburger span:nth-child(3) {
  top: 30px;
}

/* スマホメニューを開いてる時のボタン */
.hamburger.active span:nth-child(1) {
  top : 16px;
  left: 6px;
  background :#fff;
  -webkit-transform: rotate(-45deg);
  -moz-transform   : rotate(-45deg);
  transform        : rotate(-45deg);
}

.hamburger.active span:nth-child(2),
.hamburger.active span:nth-child(3) {
  top: 16px;
  background :#fff;
  -webkit-transform: rotate(45deg);
  -moz-transform   : rotate(45deg);
  transform        : rotate(45deg);
}

/* メニュー背景　*/
nav.globalMenuSp {
  position: fixed;
  z-index : 2;
  top  : 0;
  left : 0;
  color: #fff;
  background: rgba( 71,70,73,0.6 );
  text-align: center;
  width: 100%;
  transform: translateY(-100%);
  transition: all 0.6s;
}

nav.globalMenuSp ul {
  margin: 0 auto;
  padding: 0;
  width: 100%;
}

nav.globalMenuSp ul li {
  list-style-type: none;
  padding: 0;
  width: 100%;
  transition: .4s all;
}
nav.globalMenuSp ul li:last-child {
  padding-bottom: 0;
}
nav.globalMenuSp ul li:hover{
  background :#ddd;
}

nav.globalMenuSp ul li a {
  display: block;
  color: #fff;
  padding: 1em 0;
  text-decoration :none;
}

/* クリックでjQueryで追加・削除 */
nav.globalMenuSp.active {
  opacity: 100;
  display: block;
   transform: translateY(0%);
}
    </style>
</head>
<div class="hamburger">
  <span></span>
  <span></span>
  <span></span>
</div>
<nav class="globalMenuSp">
    <ul>
    <% if user_signed_in? %>
      <li class="border-radius">
        <%= link_to notifications_path, class: "" do %>
          <% if current_user.notifications.where(checked: false).exists? %>
            <i class="fa-solid fa-bell fa-shake" style="color: #f2ee7d;"></i>
          <% else %>
            <i class="fa-sharp fa-solid fa-bell"></i>
          <% end %>
          通知一覧
        <% end %>
      </li>
      <li class="border-radius">
        <%= link_to new_travel_path, class: '' do %>
        <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;新しく投稿する
        <% end %>
      </li>
      <li class="border-radius">
              <% if current_user && current_user.name %>
        <%= link_to edit_user_path(current_user), method: :get, class: "" do %>
        <i class="fa-regular fa-address-card"></i>&nbsp;&nbsp;プロフィールを編集
        <% end %>
      <% end %>
      </li>
      <li class="border-radius">
        <%= link_to "フォロー一覧", user_followings_path(current_user), class: "" %>
      </li>
            <li class="border-radius">
         <%= link_to "フォロワー一覧", user_followers_path(current_user), class: "" %>
      </li>
      <li class="border-radius">
        <%= link_to destroy_user_session_path, method: :delete, class: '' do %>
          <i class="fas fa-sign-out-alt"></i> ログアウト
        <% end %>
      </li>
    <% elsif admin_signed_in? %>
      <li>
        <%= link_to "投稿一覧", admin_travels_path %>
      </li>
      <li>
        <%= link_to "ユーザー一覧", admin_users_path %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to root_path, class: '' do %>
          <i class="fas fa-home"></i> トップページ
        <% end %>
      </li>
      <li>
        <%= link_to new_user_registration_path, class: '' do %>
          <i class="fas fa-user-plus"></i> 新規登録
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path, class: '' do %>
          <i class="fas fa-sign-in-alt"></i> ログイン
        <% end %>
      </li>
    <% end %>
    </ul>
</nav>
<script>
$(function() {
    $('.hamburger').click(function() {
        $(this).toggleClass('active');

        if ($(this).hasClass('active')) {
            $('.globalMenuSp').addClass('active');
        } else {
            $('.globalMenuSp').removeClass('active');
        }

    });
});
//メニュー内を閉じておく
$(function() {
    $('.globalMenuSp a[href]').click(function() {
        $('.globalMenuSp').removeClass('active');
       $('.hamburger').removeClass('active');

    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripHistory</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/2b7c6e9815.js" crossorigin="anonymous"></script>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
    .background {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: -3;
      /* 背景のスタイルを追加 */
    }

/* For extend styles */
.burger_common {
  display: block;
  position: absolute;
  width: 40px;
  height: 4px;
  border-radius: 2px;
  background-color: #fff;
}
.transition_all_04s_easeinout {
  transition: all 0.3s ease-in-out;
}
.backface_visibility_hidden {
  backface-visibility: hidden;
  -webkit-backface-visibility: hidden;
}

/* Main style */
main {
  margin: 0 auto;
  transform-style: preserve-3d;
  transform: perspective(500px);
}
main #content {
  position: relative;
  top: 0;
  transition: all 0.3s ease-in-out;
  backface-visibility: hidden;
}



.burger.wrapper {
  position: absolute;
  top: 25px;
  left: 20px;
}
.burger.wrapper::before {
  content: "";
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 1;
  background-color: rgba(0, 0, 0, 0.4);
  pointer-events: none;
  transition: all 0.3s ease-in-out;
  backface-visibility: hidden;
  opacity: 0;
}
.burger.bloc {
  position: fixed;
  width: 40px;
  height: 24px;
  z-index: 3;
  top: 25px;
  left: 20px;
}
.burger.inner {
  display: block;
  position: absolute;
  width: 40px;
  height: 4px;
  border-radius: 2px;
  background-color: #fff;
  top: 50%;
  margin-top: -2px;
  transition: all 0.3s cubic-bezier(0.55, 0.055, 0.675, 0.19);
}
.burger.inner::before,
.burger.inner::after {
  display: block;
  position: absolute;
  width: 40px;
  height: 4px;
  border-radius: 2px;
  background-color: #fff;
  content: "";
}
.burger.inner::before {
  top: -10px;
  transition: top 0.1s 0.34s ease-in, opacity 0.1s ease-in-out;
}
.burger.inner::after {
  bottom: -10px;
  transition: bottom 0.1s 0.34s ease-in, transform 0.3s cubic-bezier(0.55, 0.055, 0.675, 0.19),
    -webkit-transform 0.3s cubic-bezier(0.55, 0.055, 0.675, 0.19);
}

.c {
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  width: 20%;
  overflow-y: scroll;
  -ms-overflow-style: none;
  text-align: left;
  background-color: black;
  z-index: 1; /* 修正された部分 */
  transform: translateX(-100%);
  transition: all 0.3s ease-in-out;
  backface-visibility: hidden;
}

.c::-webkit-scrollbar {
  display: none;
}
.b {
  list-style-type: none;
  margin: 80px auto;
  transition: all 0.3s cubic-bezier(0.49, 0.24, 0, 1.32) 0.2s;
  backface-visibility: hidden;
}



#nav_check {
  position: absolute;
  visibility: hidden;
}
#nav_check:checked + .burger.wrapper::before {
  opacity: 0;
  pointer-events: auto;
}
#nav_check:checked ~ .burger.inner {
  transform: rotate(225deg);
}
#nav_check:checked ~ .burger.inner::before {
  top: 0;
  opacity: 0;
}
#nav_check:checked ~ .burger.inner::after {
  bottom: 0;
  transform: rotate(-90deg);
}
#nav_check:checked ~ .c {
  transform: translateX(0);
}
#nav_check:checked ~ main #content {
  transform-origin: left center;
  transform: translateX(15vw) translateZ(-20vw) rotateY(-13deg);
  filter: blur(3px);
}


  </style>
</head>
<body class="zen-kurenaido-regular">
  <%= render 'layouts/header' %>
<% if current_user %>

  <input type="checkbox" role="button" title="menu" id="nav_check" />
<label for="nav_check" class="burger wrapper" aria-hidden="true" title="menu">
  <span class="burger bloc">
    <span class="burger inner"></span>
  </span>
</label>

<nav class="c">
  <ul class="b">
    <li>
      <h3>
        <%= link_to notifications_path, class: "" do %>
          <% if current_user.notifications.where(checked: false).exists? %>
            <i class="fa-solid fa-bell fa-shake" style="color: #f2ee7d;"></i>
          <% else %>
            <i class="fa-sharp fa-solid fa-bell"></i>
          <% end %>
          通知一覧
        <% end %>
      </h3>
    </li>
    <li>
      <h4>
        <% if current_user && current_user.name %>
          <%= link_to edit_user_path(current_user), method: :get, class: "" do %>
            <i class="fa-regular fa-address-card"></i>&nbsp;&nbsp;プロフィールを編集
          <% end %>
        <% end %>
      </h4>
    </li>
    <li>
      <h4>
        <%= link_to new_travel_path, class: '' do %>
          <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;新しく投稿する
        <% end %>
      </h4>
    </li>
    <li>
      <h4>
        <%= link_to "フォロー一覧", user_followings_path(current_user), class: "" %>
      </h4>
    </li>
    <li>
      <h4>
        <%= link_to "フォロワー一覧", user_followers_path(current_user), class: "" %>
      </h4>
    </li>
  </ul>
</nav>
<% end %>

<% if current_user %>

<% end %>
<main class="main">
  <section id="content">
    <%= render 'layouts/headernav' %>
    <%= render 'layouts/scroll' %>
    <div class='container'>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </section>
</main>
<div class="background">
  <%= render 'layouts/background' %>
</div>
</body>
</html>